# Site settings
title: Computational Science Laboratory
email: hmwoo@inu.ac.kr
# description: A fully responsive site template designed by <a href="https://html5up.net">HTML5 UP</a> and released<br />for free under the <a href="https://html5up.net/license">Creative Commons</a> license.
description: Incheon National University
baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author: Hyun-Myung Woo
street_address: 119 Academy-ro
city: Incheon
state: Incheon
zip_code: 22012
country: South Korea
# phone: +82-32-800-5114

icon: fa-laptop # Font Awesome class for your site's icon

# Social settings
facebook_url:
github_url:
gitlab_url: https://github.com/Alexpecial
# googleplus_url: https://plus.google.com/u/0/+AndrewBanchich
# instagram_url:
# linkedin_url: https://www.linkedin.com/in/larcwind
# pinterest_url:
# slack_url:
# twitter_url: https://twitter.com/andrewbanchich

# Build settings
markdown: kramdown

sass:
style: compressed